# Generated by Django 3.0.5 on 2020-08-14 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_auto_20200814_1811'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='blog',
            new_name='body',
        ),
    ]
