# Generated by Django 3.0.5 on 2020-08-14 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0003_auto_20200814_1813'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='hashkey',
            new_name='key',
        ),
    ]
