# Generated by Django 3.0.5 on 2020-08-12 10:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0003_blog_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_foruser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('blog', models.TextField(default='')),
                ('time', models.DateTimeField(default=datetime.datetime.today)),
                ('status', models.CharField(default='pending', max_length=200)),
            ],
        ),
    ]
